.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH allergyd 1 "OCT 2021" "Allergy" "User Manuals"
.
.SH "NAME"
allergyd \- serve a photo gallery over HTTP
.
.SH "SYNOPSIS"
.B allergyd
.RB [ \-d ]
.RB [ \-a
.IR listen-address ]
.RB [ \-p
.IR port ]
.RB [ --host
.IR hostname ]
\&...
.B \-r
.I root
.I index
\&...
.br
.B allergyd
.B --help
.br
.B allergyd
.B --version
.
.SH "DESCRIPTION"
.
.B allergyd
is a web server which only serves a large collection of timestamped
photos, together with textual descriptions taken from index files
in a format described in
.BR allergy (5).
There are various gallery views: by date, by month, by keyword, and so on.
.
.
.SS "URLs"
.
.IP "\fB/\fP, \fB/index.html"
The front page.
.
.IP "\fB/by-date"
All photos, newest first.
.
.IP "\fB/\fIyyyy"
All photos from a certain year, oldest first.
.
.IP "\fB/\fIyyyy\fP\-\fPmm"
Like
.BR "/\fIyyyy\fP" ,
but narrowed down further to a specific month,
and with thumbnail pictures.
.
.IP "\fB/\fIyyyy\fP\-\fPmm\fP\-\fPdd"
Like
.BR /\fIyyyy\fP\-\fPmm\fP ,
but for a single day.
.
.IP "\fB/keywords\fP, \fB/key\fP, \fB/key/\fP"
All keywords, in alphabetical order.
.
.IP "\fB/key/\fIkeyword"
All photos matching the key
.IR keyword ,
newest first.
Like the per-month and per-date pages, this one includes a thumbnail gallery.
.
.IP "\fB/\fIyyyy\fP\-\fPmm\fP\-\fPdd\fP/\fPnnnn"
A page for a single photo and its description.
.
.IP "\fB/\fIyyyy\fP\-\fPmm\fP\-\fPdd\fP_\fPnnnn\fP.jpg"
The single photo with this name.
.
.IP "\fB/thumb/\fIyyyy\fP\-\fPmm\fP\-\fPdd\fP_\fPnnnn\fP.jpg"
A much scaled down version of a certain photo.
.
.IP "\fB/css\fP, \fP/robots.txt\fP, \fB/icon"
The style sheet, the
.I "robots exclusion standard"
specification, and the favicon.
.
.
.SH "OPTIONS"
.
.IP "\fB\-d\fP, \fB--daemon\fP"
Daemonize.
.
.IP "\fB\-a\fP, \fB--address\fP \fIlisten-address"
The address to listen to.
Default: listen on all interfaces.
.\" Should be repeatable.
.
.IP "\fB\-p\fP, \fB--port\fP \fIport"
The port to listen to, instead of port 80
.RB ( http ).
.
.IP "\fB--host\fP \fIhostname"
The server name, i.e. the
.B Host
header (minus the port number, if any) allowed in requests.
You can specify multiple allowed server names \- or none, which
means allowing anything.
.\" Should support globbing.
.
.IP "\fB\-r\fP, \fB--root\fP \fIroot"
The root directory containing the actual photos.
.\" Should be repeatable.
.
.IP "\fIindex\fP ..."
.BR allergy (5)
index files describing the photos.
A photo will be served only if it's listed here.
.
.
.SH "FILES"
.
.
.SH "NOTES"
.
.B allergyd
supports HTTP 1.0 and 1.1 only.
There are no plans to support HTTP/2 or HTTP/3.
Similarly, allergyd doesn't support HTTPS.
If this worries you, run it behind a proxy (which you might want to do anyway).
.
.
.SH "BUGS"
.
.
.SH "HISTORY"
.
.B allergyd
started in 2010 as an attempt to write an NNTP server called
.IR gresabladet ,
suitable for keeping local newsgroups in a team or organization.
(There was still some hope for traditional Internet protocols and open standards at that time.)
I also wanted to learn techniques for reliably serving TCP, without threads or forking,
or underdocumented and overhyped frameworks like Boost.Asio.
When that work stalled, around 2012, I wanted to turn the code into a
lightweight HTTP server for static files, named
.IR outnumbered .
Then I got absorbed by paid work for a number of years,
and then I got disillusioned with Python, which I had used for
generating and/or serving photo galleries under the name
.I allergy
since 2001.
So I figured that I could get a useful and feasible project by combining the code from
.I outnumbered/gresabladet
and the task from
.IR allergy .
.
.
.SH "SEE ALSO"
.
.BR allergy (5),
.BR RFC\~7231 .
.
.SH "AUTHOR"
J\(:orgen Grahn \[fo]grahn+src@snipabacken.se\[fc].
.
.
.SH "LICENSE"
The GNU General Public License (GPL) version 2 or (at your option) version 3.
