.ss 12 0
.de BP
.IP "\\fB\\$*"
..
.
.TH allergy 7 "AUG 2014" "Allergy" "User Manuals"
.
.
.SH "NAME"
allergy \- serve photo galleries over HTTP
.
.
.SH "URLs"
.
The web interface of
.B allergy_index
looks as follows:
.
.IP "\fB/\fP, \fB/index.html"
The front page.
.
.IP "\fB/by-date"
All photos, newest first.
.
.ig
.IP "\fB/\fIcategory"
All photos in category
.IR category ,
by reverse date.
A category is just a fancy name for the directory the photo resides in,
relative to the base path.
..
.
.IP "\fB/\fIyear"
All photos from a certain year (given as
.IR yyyy ),
oldest first.
.
.IP "\fB/\fIyear\fB\-\fPmonth"
Like
.BR /\fIyear\fP ,
but narrowed down further to a specific month.
.IP
Also, this kind contains a thumbnail gallery
like that of
.BR allergy (1).
It assumes that there are pre-generated thumbnail images,
as created by that utility.
.
.IP "\fB/\fIyear\fB\-\fPmonth\fB\-\fIday"
Like
.BR /\fIyear\fP\-\fImonth\fP ,
but for a single day.
.
.IP "\fB/\fIimage"
A single photo named
.IR image .
.
.IP "\fB/thumb/\fIimage"
The thumbnail for
.IR image ,
if present.
.
.IP "\fB/keywords\fP, \fB/key\fP, \fB/key/\fP"
All keywords, in alphabetical order.
.
.IP "\fB/key/\fIkeyword"
All photos matching the key
.IR keyword ,
newest first.
Like the by-month and by-date pages, this one includes a thumbnail gallery.
.
.IP "\fB/css"
The style sheet applied to all pages.
.
.IP "\fB/robots.txt"
The
.I "robots exclusion standard"
document,
preventing mirroring or indexing of the descriptions and photos.
.
.
.SH "HTTP REQUESTS"
.
.BP User-Agent
.BP Host
.BP Accept
.BP Accept-Language
.BP Accept-Encoding
.BP Connection
.
.
.SH "HTTP RESPONSES"
.
.BP Date
.BP Server
.BP Last-Modified
.BP ETag
.BP Accept-Ranges
.BP Vary
.BP Content-Encoding
.BP Content-Length
.BP Keep-Alive
.BP Connection
.BP Content-Type
.
.
.SH "SEE ALSO"
.BR allergy (1).
