.\" $Id: allergy.1,v 1.14 2004-05-31 14:57:03 grahn Exp $
.\" $Name:  $
.\" 
.\"
.TH allergy 1 "MAY 2004" "Allergy" "User Manuals"
.SH "NAME"
allergy \- thumbnail and HTML picture gallery creator
.SH "SYNOPSIS"
.B allergy [\-k]
.I file
.B ...
.
.SH "DESCRIPTION"
.B Allergy
takes one or more files (or else standard input),
concatenates them,
processes embedded gallery descriptions into HTML code
for displaying thumbnail images
(generating the thumbnails meanwhile)
and writes the result to standard output.
.
.SH "OPTIONS"
.IP -k
(keep) Never regenerate existing thumbnails, even if they are
newer than the source image.
This is useful if you
.I know
you have the exact thumbnails you want, but something keeps messing up
the timestamps.
.
.SH "GENERAL INPUT SYNTAX"
Everything in the input outside the gallery descriptions
is output as-is. Presumably, it consists of HTML code.
.LP
Input may contain one or more gallery descriptions. These are
bracketed as follows:
.IP
.ft CW
.nf
\\begin{gallery}
\&...
\\end{gallery}
.fi
.LP
The gallery description consists of optional definitions lines
which determine general characteristics of the gallery to be rendered,
followed by a list of file names and descriptions.
Empty lines and lines starting with a hash are treated as comments
and ignored.
.LP
Additionally, lines starting with whitespace are considered as
continuation lines, much like in Internet mail headers \(em
.BR allergy (1)
sees them as part of a logical line starting with the previous line
which starts with a non-whitespace character.
This is useful when you write long caption texts.
.
.SH "GALLERY DEFINITIONS"
The following definitions are recognized:
.IP
.ft CW
\\grid{\fIcols\fP, n}
.LP
Layout of the gallery \(em generates a HTML
.B <table>
with
.I cols
columns (default: four) and enough rows to fit all images.
Caption text, if any, will appear as the
.B title
attribute of the thumbnail image.
This is the default gallery layout.
.IP
.ft CW
\\list{}
.LP
Alternate layout strategy \(em generates a
.B <div>
containing a series of paragraphs,
each containing the thumbnail and the caption text.
.I list
is more useful than
.I grid
when you have a lot to say about each picture.
.IP
.ft CW
\\class{\fIname\fP}
.LP
Sets the
.B class
attribute on the HTML construct (i.e. the
.B <table>
or the
.BR <div> )
making up the gallery.
This is useful for controlling rendering of the page using CSS.
Default: not set.
.IP 
.ft CW
\\bounded{\fIwidth\fP, \fIheight\fP}
.LP
Specifies the dimensions of the thumbnail image. Images will be scaled
so that they fit in a rectangle of the given size,
while preserving the aspect ratio.
Default: (140,100).
.IP
.ft CW
\\quality{\fIn\fP}
.LP
Quality of the generated JPEG thumbnails, from 0 (worst) to 100 (best).
Default: 30.
.
.SH "IMAGE DEFINITIONS"
Images to be included in the gallery are defined by lines on the forms
.IP 
.ft CW
.nf
filename-or-pattern : caption-text
filename-or-pattern : caption-text
  more caption-text
  ...
filename-or-pattern
.fi
.LP
The images can be specified one at a time, using filename expansion, or
using a combination of the two.
The filename expansion is implemented by
\(lqglobbing\(rq, which expands patterns in the manner of
.BR csh (1)
\(em things like
.BR * ,
.BR ? ,
and
.B []
are supported.
.LP
The patterns never match a file name starting with an underscore \(em
those are reserved for thumbnail file names.
.LP
Images are laid out in the order of appearance in the input file.
Patterns expand to a sorted (usually) list of all matching file names.
For each gallery definition, duplicate image definitions are removed
by removing all but the first one in the list. This makes it possible
to move important images to near the top and let the others appear in
order below. For example:
.IP 
.ft CW
.nf
foo.png
bar.png
*.png
.fi
.LP
Files that cannot be thumbnailed will appear as plain links in the
output. Files that
.I can
be inlined are image files recognized by
whatever version of the \fIPython Imaging Library\fP
you have installed.
.LP
The caption text may be any piece of valid HTML if you intend to
format the gallery as a list.
If you use the grid layout, it must be plain text.
.
.SH "GENERATED HTML CODE"
The general idea is to generate strictly conforming code, and let
the user take care of specific rendering details using style sheets,
supported by the \fIclass\fP definition described above.
.LP
Inline images (i.e. the thumbnails) are given an
.B alt
text, which simply is the filename, bracketed.
They may also be given, as described above, a
.B title
containing the caption text.
.LP
Thumbnail pictures are named as the originals, but with an underscore
character as prefix.
.
.SH "BUGS"
.IP \(bu
All names of thumbnail images are expected to begin
with an underscore ('_'). Thumbnails are never generated
for these files, even if the input explicitly requests it.
.IP \(bu
When using generated tables, are they browser-friendly,
or do they delay rendering
unnecessarily over slow connections?
.IP \(bu
Conformance to W3C standards has not been verified.
.IP \(bu
The input syntax is messy, brittle and restrictive.
.IP \(bu
Error handling and error reporting is probably unsatisfactory.
.
.SH "DEPENDENCIES"
.BR allergy (1)
depends on external utilities for converting and scaling thumbnail images.
These are
.BR pmnfile ,
.BR pmnscale
and
various format converters (e.g.
.BR pngtopnm )
from the
.B netpbm
toolkit, and
.BR cjpeg 
and
.BR djpeg
from the
.B libjpeg
distribution.
.
.SH "AUTHOR"
J\(:orgen Grahn <jgrahn@algonet.se>
.
.SH "LICENSE"
BSD-style, without (non-) advertising clause.
