.\" $Id: allergy.1,v 1.6 2001-10-02 10:03:04 grahn Exp $
.\" $Name:  $
.\" 
.\"
.TH allergy 1 "AUG 2001" "Allergy" "User Manuals"
.SH "NAME"
allergy \- thumbnail and HTML picture gallery creator
.SH "SYNOPSIS"
.B allergy
.I file
.B ...
.SH "DESCRIPTION"
.B Allergy
takes one or more files (or else standard input),
concatenates them,
processes embedded gallery descriptions into HTML code
for displaying thumbnail images
and writes the result to standard output.

It generates the thumbnail images as well, with the help of external
utilities. To speed up the process, thumbnails that exist and are
newer than the source image will not be regenerated.
.SH "GENERAL INPUT SYNTAX"
Everything in the input outside the gallery descriptions
is output as-is. Presumably, it consists of HTML code.

Input may contain one or more gallery descriptions. These are
delimited as follows:
.IP
.ft CW
\\begin{gallery}
.br
 ...
.br
\\end{gallery}
.LP
The gallery description consists of optional definitions lines
which determine general characteristics of the gallery to be rendered,
followed by a list of file names and descriptions.
Empty lines and lines starting with a hash are treated as comments
and ignored.

Additionally, lines starting with whitespace are considered as
continuation lines, much like in Internet mail headers \(em
.BR allergy (1)
sees them as part of a logical line starting with the previous line
which starts with a non-whitespace character.
This is useful when you write long caption texts.
.SH "GALLERY DEFINITIONS"
The following definitions are recognized:
.IP
.ft CW
\\grid{
.IR cols ,
n}
.LP
Layout of the gallery \(em generates a HTML table with
.I cols
columns and enough rows to fit all images.
.br
Default: four columns.
.IP
.ft CW
\\class{
.IR classname }
.LP
Sets the
.B class
attribute on the HTML construct (i.e. the
.BR <table> )
making up the gallery.
This is useful for controlling rendering of the page using CSS.
.br
Default: not set.
.IP 
.ft CW
\\bounded{
.IR width ,
.IR height }
.LP
Specifies the dimensions of the thumbnail image. Images will be scaled
so that they fit in a rectangle of size (
.IR width ,
.IR height ),
while preserving the aspect ratio.
.br
Default: (140,100).
.IP
.ft CW
\\thumb{
.IR substitution }
.LP
Controls the generation of thumbnail filenames from the corresponding
full-size image filename.
.I substitution
is a
.BR perl (1)
expression which is evaluated with
.B $_
set to the file name. The value of the expression is used as the thumbnail name.
.br
Default: '_' prefix and 'jpg' suffix:
.ft CW
s/(.+)\\..+/_$1.jpg/
.IP
.ft CW
\\quality{
.IR no }
.LP
Quality of the generated JPEG thumbnails, from 0 (worst) to 100 (best).
.br
Default: 30.
.SH "IMAGE DEFINITIONS"
Images to be included in the gallery are defined by lines on the forms
.IP 
.ft CW
filename-or-pattern : caption-text
.br
filename-or-pattern : caption-text
.br
  more caption-text
.br
  ...
.br
filename-or-pattern
.LP
The images can be specified one at a time, using filename expansion, or
using a combination of the two.
The filename expansion is implemented by the
.BR perl (1)
.B glob
function, which expands patterns in the manner of
.BR sh (1)
(or is it
.BR csh (1)?)
\(em things like
.BR * ,
.BR ? ,
.B []
and
.B {}
are supported.

Images are laid out in the order of appearance in the input file.
Patterns expand to a sorted (usually) list of all matching file names.
For each gallery definition, duplicate image definitions are removed
by removing all but the first one in the list. This makes it possible
to move important images to near the top and let the others appear in
order below. For example:
.IP 
.ft CW
foo.png
.br
bar.png
.br
*.png
.LP
Files that cannot be thumbnailed will appear as plain links in the
output. Files that
.I can
be inlined are image files with extensions recognized by
.BR allergy ,
namely
"jpg",
"jpeg",
"png",
"gif",
"iff" and
"ilbm".

The caption text may be any piece of valid HTML.
It will be laid out within the same table cell as the image,
with a
.B <br>
inbetween.

The text is interpolated before use, and
.BR perl (1)
variables within it will be substituted with their values.
Currently, only
.IP 
.ft CW
$name
.LP
is useful;
it will be interpolated as the file name of the actual image.

Caption texts aren't all that useful right now; they tend to render
as larger than the actual thumbnail and mess up the table.
.SH "GENERATED HTML CODE"
The general idea is to generate strictly conforming code, and let
the user take care of specific rendering details using style sheets.

The focus is on navigation and presentation of the images themselves,
on performance and browser independence \(em not on bells and whistles.
Visual design of the gallery is best accomplished through style sheets.

Images are given an
.B ALT
text, which simply is the filename, bracketed.
.SH "BUGS"
.IP \(bu
All names of thumbnail images are expected to being
with an underscore ('_'). Thumbnails are never generated
for these files, even if the input explicitly requests it.
.IP \(bu
Are the generated tables browser-friendly, or do they delay rendering
unnecessarily over slow connections?
.IP \(bu
Conformance to W3C standards has not been verified.
.IP \(bu
Since
.BR allergy (1)
evaluates arbitrary perl code in its input file,
you should be careful when generating galleries from unknown sources.
.IP \(bu
The input syntax is messy, brittle and restrictive.
.IP \(bu
File type detection is based on filename extensions rather than analysis
of actual contents.
.IP \(bu
Error handling and error reporting is probably unsatisfactory.
.SH "DEPENDENCIES"
.BR allergy (1)
depends on external utilities for converting and scaling thumbnail images.
These are
.BR pmnfile ,
.BR pmnscale
and
various format converters (e.g.
.BR pngtopnm )
from the
.B netpbm
toolkit, and
.BR cjpeg 
and
.BR djpeg
from the
.B libjpeg
distribution.
.SH "AUTHOR"
Jörgen Grahn <jgrahn@algonet.se>
.SH "LICENSE"
BSD-style, without (non-) advertising clause.
