#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
#
# $Id: allergy_index,v 1.4 2008-07-19 08:49:29 grahn Exp $
# $Name:  $
#
# Copyright (c) 2008 Jörgen Grahn <grahn+src@snipabacken.se>
# All rights reserved.
#
"""build a html photo index
"""
import re
import os.path
import os
import sys

from photobase import Photobase

def reversedate(s):
    """Transform a standard 'yyyy-mm-dd' date string
    to the less formal 'd.m.yyyy' format popular in Sweden.
    """
    date = map(int, s.split('-'))
    date.reverse()
    return '%d.%d.%d' % tuple(date)


class Generator(object):

    def __init__(self, photobase):
        self._pb = photobase
        self._by_date = self._pb.files.values()
        self._by_date.sort(key = lambda x: x.datetime, reverse = True)
        
    def _generate_toc(self, f):
        w = f.write
        w('efter datum\n'
          'index till nyckelord\n'
          'efter nyckelord\n')

    def _generate_timeline(self, f):
        w = f.write
        py = pym = pdate = pdesc = None
        for p in self._by_date:
            date, time = p.datetime.split(None, 2)
            y, m, _ = p.datetime.split('-', 2)
            desc = p.description
            if py != y:
                w('%s\n' % y)
                py = y
            if pym != (y, m):
                w('  %s\n' % m)
                pym = y, m
            if pdate != date:
                pdate = date
            else:
                date = ''
            if pdesc != desc:
                pdesc = desc
            else:
                desc = ''
            w('    %10s %5s -- %s\n' % (date, time,
                                        desc))

    def _generate_index_index(self, f):
        w = f.write
        kk = self._pb.keys.keys()
        kk.sort(key = str.lower)
        w(' -- '.join(kk))
        w('\n')

    def _generate_index(self, f):
        w = f.write
        kk = self._pb.keys.keys()
        kk.sort(key = str.lower)
        for k in kk:
            w('%s\n' % k)
            pb = self._pb.keys[k][:]
            pb.sort(key = lambda x: x.datetime, reverse = False)
            pdate = pdesc = None
            for p in pb:
                date, time = p.datetime.split(None, 2)
                desc = p.description
                if pdate != date:
                    pdate = date
                else:
                    date = ''
                if pdesc != desc:
                    pdesc = desc
                else:
                    desc = ''
                w('    %10s %5s -- %s\n' % (date, time,
                                            desc))


    def generate(self, f):
        self._generate_toc(f)
        f.write('\n')
        self._generate_timeline(f)
        f.write('\n')
        self._generate_index_index(f)
        f.write('\n')
        self._generate_index(f)


def generate(pb, f):
    Generator(pb).generate(f)


def cvs_says(dollarname='$Name:  $'):
    import re
    m = re.match(r'\$'r'Name:\s+(.+?)-(\d+(-\d+)*)\D', dollarname)
    if not m: return ('allergy', 'unknown')
    return m.group(1), m.group(2).replace('-', '.')


if __name__ == "__main__":
    import getopt
    import fileinput
    import os

    prog = os.path.basename(sys.argv[0])

    usage = 'usage: %s [-f file] ... [-e] [-k] [-v | -V] file ...' % prog

    try:
        opts, files = getopt.getopt(sys.argv[1:], 'f:ekvV',
                                    ['help',
                                     'version'])
    except getopt.GetoptError, s:
        print >>sys.stderr, s
        print >>sys.stderr, usage
        sys.exit(1)
    clobber = 1
    verbosity = 0
    descriptions = []
    exiftime = None
    for option, value in opts:
        if option == '-f': descriptions.append(value)
        if option == '-e': exiftime = ExifTime()
        if option == '-k': clobber = 0
        if option == '-v': verbosity = 2
        if option == '-V': verbosity = 1
        if option == '--help':
            print usage
            sys.exit(0)
        if option == '--version':
            print prog
            print '%s, version %s' % cvs_says()
            print 'Copyright (c) 2008 Jörgen Grahn.'
            sys.exit(0)

    if descriptions:
        photobase = Photobase(descriptions)
    else:
        photobase = None

    generate(photobase, sys.stdout)
